apiVersion: apps/v1
kind: Deployment
metadata:
  name: otwongk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otwongk
  template:
    metadata:
      labels:
        app: otwongk
    spec:
      containers:
      - image: okteto.dev/otwongk:latest
        name: otwongk
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "c917fccd-ad88-4218-a3ae-4424dcb79ea5"
        - name: Vless_Path
          value: "/vlessw54h6ybrs5gyd5y2g"
        - name: Vmess_UUID
          value: "c917fccd-ad88-4218-a3ae-4424dcb79ea5"
        - name: Vmess_Path
          value: "/vmess3tyrtdg56sey45rbty"
        - name: Share_Path
          value: "/v2link"
